### ISSUE TITLE
Need to setup tests

### ISSUE THREAD

**Issue by georgesnow** [georgesnow/netmiko#1]
need to setup test files to run

**Comment by georgesnow** [comment]
================================= test session starts ==================================
platform linux -- Python 3.6.8, pytest-5.0.1, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /usr/local/lib/python3.6/dist-packages/netmiko/tests
collected 14 items

test_netmiko_show.py::test_disable_paging FAILED                                 [  7%]
test_netmiko_show.py::test_ssh_connect PASSED                                    [ 14%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                 [ 21%]
test_netmiko_show.py::test_send_command_timing FAILED                            [ 28%]
test_netmiko_show.py::test_send_command FAILED                                   [ 35%]
test_netmiko_show.py::test_send_command_textfsm FAILED                           [ 42%]
test_netmiko_show.py::test_send_command_genie FAILED                             [ 50%]
test_netmiko_show.py::test_base_prompt PASSED                                    [ 57%]
test_netmiko_show.py::test_strip_prompt PASSED                                   [ 64%]
test_netmiko_show.py::test_strip_command PASSED                                  [ 71%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                            [ 78%]
test_netmiko_show.py::test_clear_buffer PASSED                                   [ 85%]
test_netmiko_show.py::test_enable_mode PASSED                                    [ 92%]
test_netmiko_show.py::test_disconnect PASSED                                     [100%]

**Comment by georgesnow** [comment]
================================= test session starts ==================================
platform linux -- Python 3.6.8, pytest-5.1.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /usr/local/lib/python3.6/dist-packages/netmiko/tests
collected 14 items

test_netmiko_show.py::test_disable_paging PASSED                                 [  7%]
test_netmiko_show.py::test_ssh_connect PASSED                                    [ 14%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                 [ 21%]
test_netmiko_show.py::test_send_command_timing PASSED                            [ 28%]
test_netmiko_show.py::test_send_command PASSED                                   [ 35%]
test_netmiko_show.py::test_send_command_textfsm FAILED                           [ 42%]
test_netmiko_show.py::test_send_command_genie FAILED                             [ 50%]
test_netmiko_show.py::test_base_prompt PASSED                                    [ 57%]
test_netmiko_show.py::test_strip_prompt PASSED                                   [ 64%]
test_netmiko_show.py::test_strip_command PASSED                                  [ 71%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                            [ 78%]
test_netmiko_show.py::test_clear_buffer PASSED                                   [ 85%]
test_netmiko_show.py::test_enable_mode PASSED                                    [ 92%]
test_netmiko_show.py::test_disconnect PASSED                                     [100%]

**Comment by georgesnow** [comment]
textfsm and command_genie left to fix

**Comment by dBitech** [comment]
I'd like to recommend that you use the full verbose variations of the commands, so for example.
```config save``` should be ```configuration save```

**Comment by georgesnow** [comment]
@dBitech good call I had set up the commands for testing. I will go back and fix those.

**Comment by georgesnow** [comment]
@dBitech fixed. I have the tests and some other pieces to upload, but this specific issue has been fixed.
